package Frames;


import BeanClasses.BatchBean;
import BeanClasses.DepartmentBean;
import BeanClasses.FacultyBean;
import BeanClasses.ListItem;
import BeanClasses.ProgramBean;
import DatabaseManager.DatabaseManager;
import java.awt.event.ActionEvent;
import java.util.Vector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Danish
 */
public class BatchFrame extends javax.swing.JFrame {

    /**
     * Creates new form BatchFrame
     */
    public BatchFrame() {
        initComponents();

        	shiftComboBox.addItem(new ListItem("M","MORNING"));
		shiftComboBox.addItem(new ListItem("E","EVENING"));
		shiftComboBox.addItem(new ListItem("N","NOON"));

		groupComboBox.addItem(new ListItem("E","ENGINEERING"));
		groupComboBox.addItem(new ListItem("M","MEDICAL"));
		groupComboBox.addItem(new ListItem("C","COMMERCE"));
		groupComboBox.addItem(new ListItem("G","GENERAL"));
     
        getFaculty();
    }
  private void getFaculty(){
	try{
                Vector v=DatabaseManager.getFaculty();
		facultyComboBox.removeAllItems();
		for(int i=0; i<v.size(); i++)
			facultyComboBox.addItem(v.elementAt(i));

	}catch(Exception e){
		e.printStackTrace();
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}//end method
  private void getDepartment(){
	FacultyBean bean=(FacultyBean)facultyComboBox.getSelectedItem();
	if(bean==null)return;

	try{
	          Vector v=DatabaseManager.getDepartment( bean.getFacId() );
	      deptComboBox.removeAllItems();
		for(int i=0; i<v.size(); i++)
			deptComboBox.addItem(v.elementAt(i));	
	}catch(Exception e){
		e.printStackTrace();
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}
  private void getProgram(){
	DepartmentBean bean=(DepartmentBean)deptComboBox.getSelectedItem();
	if(bean==null)return;

	try{
	          Vector v=DatabaseManager.getProgram( bean.getDeptId() );
	          progComboBox.removeAllItems();
		for(int i=0; i<v.size(); i++)
			progComboBox.addItem(v.elementAt(i));	
	}catch(Exception e){
		e.printStackTrace();
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}  
  private void getBatch(){
	ProgramBean bean=(ProgramBean)progComboBox.getSelectedItem();
	if(bean==null)return;

	try{
	          Vector v=DatabaseManager.getBatch( bean.getProgId() );
	           batchYearList.setListData(v); 		
	}catch(Exception e){
		e.printStackTrace();
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batchLabel = new javax.swing.JLabel();
        facultyLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        progLabel = new javax.swing.JLabel();
        batchIdLabel = new javax.swing.JLabel();
        batchYearLabel = new javax.swing.JLabel();
        shiftLabel = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        remarksLabel = new javax.swing.JLabel();
        batchListLabel = new javax.swing.JLabel();
        facultyComboBox = new javax.swing.JComboBox();
        deptComboBox = new javax.swing.JComboBox();
        progComboBox = new javax.swing.JComboBox();
        shiftComboBox = new javax.swing.JComboBox();
        groupComboBox = new javax.swing.JComboBox();
        batchIdTextField = new javax.swing.JTextField();
        batchYearTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        batchYearList = new javax.swing.JList();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1030, 677));
        getContentPane().setLayout(null);

        batchLabel.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        batchLabel.setText("BATCH");
        getContentPane().add(batchLabel);
        batchLabel.setBounds(460, 10, 190, 50);

        facultyLabel.setText("FACULTY");
        getContentPane().add(facultyLabel);
        facultyLabel.setBounds(70, 110, 68, 20);

        deptLabel.setText("DEPARTMENT");
        getContentPane().add(deptLabel);
        deptLabel.setBounds(70, 160, 102, 20);

        progLabel.setText("PROGRAMS");
        getContentPane().add(progLabel);
        progLabel.setBounds(70, 210, 84, 20);

        batchIdLabel.setText("BATCH ID");
        getContentPane().add(batchIdLabel);
        batchIdLabel.setBounds(70, 270, 73, 20);

        batchYearLabel.setText("BATCH YEAR");
        getContentPane().add(batchYearLabel);
        batchYearLabel.setBounds(70, 320, 96, 20);

        shiftLabel.setText("SHIFT");
        getContentPane().add(shiftLabel);
        shiftLabel.setBounds(290, 320, 44, 20);

        groupLabel.setText("GROUP");
        getContentPane().add(groupLabel);
        groupLabel.setBounds(460, 320, 70, 20);

        remarksLabel.setText("REMARKS");
        getContentPane().add(remarksLabel);
        remarksLabel.setBounds(70, 380, 80, 20);

        batchListLabel.setText("BATCH YEAR");
        getContentPane().add(batchListLabel);
        batchListLabel.setBounds(640, 230, 96, 20);

        facultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(facultyComboBox);
        facultyComboBox.setBounds(190, 110, 410, 26);

        deptComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(deptComboBox);
        deptComboBox.setBounds(190, 160, 410, 26);

        progComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(progComboBox);
        progComboBox.setBounds(190, 210, 410, 26);

        getContentPane().add(shiftComboBox);
        shiftComboBox.setBounds(360, 320, 90, 26);

        getContentPane().add(groupComboBox);
        groupComboBox.setBounds(530, 320, 80, 26);
        getContentPane().add(batchIdTextField);
        batchIdTextField.setBounds(190, 270, 420, 26);
        getContentPane().add(batchYearTextField);
        batchYearTextField.setBounds(190, 320, 80, 26);

        remarksTextArea.setColumns(20);
        remarksTextArea.setRows(5);
        jScrollPane1.setViewportView(remarksTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 380, 420, 150);

        batchYearList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                batchYearListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(batchYearList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(640, 270, 350, 260);

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(190, 570, 93, 50);

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(300, 570, 93, 50);

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(410, 570, 81, 50);

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(520, 570, 90, 50);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(890, 570, 89, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
            if(updateButton==evt.getSource())  
                updateBatch();        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
//          new MainFrame().setVisible(true);
//          dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void facultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyComboBoxActionPerformed
        getDepartment();        // TODO add your handling code here:
    }//GEN-LAST:event_facultyComboBoxActionPerformed

    private void deptComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptComboBoxActionPerformed
        getProgram();        // TODO add your handling code here:
    }//GEN-LAST:event_deptComboBoxActionPerformed

    private void progComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progComboBoxActionPerformed
        getBatch();        // TODO add your handling code here:
    }//GEN-LAST:event_progComboBoxActionPerformed

    private void batchYearListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_batchYearListValueChanged
          BatchBean bean=(BatchBean)batchYearList.getSelectedValue();
   if(bean==null)return;

   batchIdTextField.setText( ""+bean.getBatchId());
      shiftComboBox.setSelectedItem( bean.getShift());
   groupComboBox.setSelectedItem( bean.getGroupDesc());
   batchYearTextField.setText( ""+bean.getBatchYear());
   remarksTextArea.setText( bean.getRemarks());  

   for(int i=0; i<shiftComboBox.getItemCount(); i++){
	ListItem item=(ListItem)shiftComboBox.getItemAt(i);
	if(item.getKey().equals(bean.getShift()))
		shiftComboBox.setSelectedItem(item);
}


for(int i=0; i<groupComboBox.getItemCount(); i++){
	ListItem item=(ListItem)groupComboBox.getItemAt(i);
	if(item.getKey().equals(bean.getGroupDesc()))
		groupComboBox.setSelectedItem(item);
}
// TODO add your handling code here:
    }//GEN-LAST:event_batchYearListValueChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       if(addButton==evt.getSource())
           addBatch();//  if(addButton==e.getSource)      addFaculty();      // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
      if(clearButton==evt.getSource())
        clear(); // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if(deleteButton==evt.getSource())
        deleteBatch();// TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addBatch(){
     ProgramBean bean=(ProgramBean)progComboBox.getSelectedItem();
     if(bean==null)return;

   // int batchId = Integer.parseInt(batchIdTextField.getText());
    int batchYear = Integer.parseInt(batchYearTextField.getText());
		ListItem shiftItem=(ListItem)shiftComboBox.getSelectedItem();
		ListItem groupItem=(ListItem)groupComboBox.getSelectedItem();    
   // String shift=shiftComboBox.getSelectedItem().toString();
   // String groupDesc=groupComboBox.getSelectedItem().toString();
    String remarks=remarksTextArea.getText();

    try{
               	int rows=DatabaseManager.addBatch(	bean.getProgId(),batchYear,shiftItem.getKey(),groupItem.getKey(),remarks);
	if(rows>=1){
	        	javax.swing.JOptionPane.showMessageDialog(this,rows+" Records Inserted."); 
		clear();
		getBatch();				
	}
    }catch(Exception e){
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
    }

}   //end
private void deleteBatch(){
    BatchBean bean = (BatchBean)batchYearList.getSelectedValue();
    if(bean==null)return;
    try{
           int rows = DatabaseManager.deleteBatch(bean.getBatchId());
           if(rows>=1){
           javax.swing.JOptionPane.showMessageDialog(this,rows+"Record Removed.");
           getBatch();
           clear();
           }
    }catch(Exception e){
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
    }

}
private void updateBatch(){
     BatchBean bean=(BatchBean)batchYearList.getSelectedValue();
     if(bean==null)return;

    int batchYear = Integer.parseInt(batchYearTextField.getText());
    String shift=shiftComboBox.getSelectedItem().toString();
    String groupDesc=groupComboBox.getSelectedItem().toString();
    String remarks=remarksTextArea.getText();
     try{
	int rows=DatabaseManager.updateBatch(bean.getBatchId(),batchYear,shift,groupDesc,remarks);
	if(rows>=1){
	    javax.swing.JOptionPane.showMessageDialog(this,rows+" Record Modified.");
	    getBatch();
	    clear();
        	}
     }catch(Exception e){
         e.printStackTrace();
         javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
     } 
}

private void clear(){
    batchIdTextField.setText("");
    batchYearTextField.setText("");
    remarksTextArea.setText("");
} 

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel batchIdLabel;
    private javax.swing.JTextField batchIdTextField;
    private javax.swing.JLabel batchLabel;
    private javax.swing.JLabel batchListLabel;
    private javax.swing.JLabel batchYearLabel;
    private javax.swing.JList batchYearList;
    private javax.swing.JTextField batchYearTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox deptComboBox;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JComboBox facultyComboBox;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JComboBox groupComboBox;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox progComboBox;
    private javax.swing.JLabel progLabel;
    private javax.swing.JLabel remarksLabel;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JComboBox shiftComboBox;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
